### ISSUE TITLE
[Feature] CARD Timestamped 설정

### ISSUE THREAD

**Issue by JihyeChu** [JihyeChu/Trello-Project#11]
@SpringBootApplication을 우선적으로 설정해 주었고,
![image](https://github.com/JihyeChu/Trello-Project/assets/51440636/129329ef-0d7c-489c-a4df-0e61a74f7ec8)

TimeStamped 클래스 생성되어있고, CardEntity는 TimeStamped를 상속받고 있다.

![image](https://github.com/JihyeChu/Trello-Project/assets/51440636/48b1a02e-b753-4cc5-9f76-7e5ca3d0bf8f)

ResponseDto에도 가져오는 변수 잘 넣어줬다. 
![image](https://github.com/JihyeChu/Trello-Project/assets/51440636/a5381dd0-68db-41c2-b4e6-2b33734ec47f)

배운대로 기본적인 설정들을 해줬는데 카드 생성시 createAt에 null값이 들어간다.

**Comment by MI-Ryeon** [comment]
![image](https://github.com/JihyeChu/Trello-Project/assets/133615790/81dbec7b-eabb-4c0a-9ef8-6285383c165b)
@EnableJpaAuditing 어노테이션으로 createAd, modifiedAt 활성화 완료
![image](https://github.com/JihyeChu/Trello-Project/assets/133615790/3ab3d01b-e6f4-49fe-8f99-ff9b66a18a27)
